db:
  host: "localhost"
  port: 3307
  username: "root"
  password: "root"
  dbName: "friends_management"

# db:
#   host: your_db_host
#   port: your_db_port
#   username: your_db_user
#   password: your_db_password
#   dbName: your_db_name
