// Code generated by sql2gorm. DO NOT EDIT.
package friend_model

import (
	"time"
)

type Blocks struct {
	BlockerID int       `gorm:"column:blocker_id;primary_key"`
	BlockedID int       `gorm:"column:blocked_id;NOT NULL"`
	CreatedAt time.Time
}